name: benchmark

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
#   cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  PYTHON_VERSION: "3.12"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Install Rust toolchain"
        run: rustup show

      - name: "Install codspeed"
        run: cargo install --git https://github.com/CodSpeedHQ/codspeed-rust --branch fix/display-run-error
        # uses: taiki-e/install-action@v2
        # with:
        #   tool: cargo-codspeed

      - uses: Swatinem/rust-cache@v2

      - name: "Install requirements and prime cache"
        run: |
          sudo apt-get install -y libsasl2-dev libldap2-dev libkrb5-dev
          cargo run --bin uv -- venv --cache-dir .cache
          cargo run --bin uv -- pip install -r scripts/requirements/airflow.in --cache-dir .cache

      - name: "Build benchmarks"
        run: cargo codspeed build --features codspeed -p bench

      - name: "Run benchmarks"
        uses: CodSpeedHQ/action@v2
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
